### ISSUE TITLE
Show status (e.g. pending) with style that does not look like a button

### ISSUE THREAD

**Issue by bmamlin** [personalcancertoolkit/openmrs-module-patientportaltoolkit#128]
In CancerBuddies view, show pending as status style for relationships waiting on someone else and show a button for connections awaiting the user's approval. This approach should be used system-wide.

**Comment by maurya** [comment]
Updated design to look better
<img width="1541" alt="screen shot 2017-05-22 at 11 33 44 am" src="https://cloud.githubusercontent.com/assets/1560244/26316550/9e219e1a-3ee2-11e7-8122-3e4e526750c6.png">
