### ISSUE TITLE
Dr Should be able to edit patient's Treatment Summaries

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#156]

**Comment by uladkasach** [comment]
By treatment summaries does this issue refer to the 'Comments' field of input the user submits for 'Mark Completed'?

**Comment by maurya** [comment]
No, this is in the treatments tab, where you enter or edit treatments. This feature might already be done, but need to verify

**Comment by maurya** [comment]
Verified, Doctor can edit patient treatments
