### ISSUE TITLE
Systolic and diastolic should be in reverse

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#202]

**Comment by uladkasach** [comment]
This is solved with pull request #220 . Solution creates a method by which question ordering can be specified for any concepts and any subset of relevant questions.

![image](https://cloud.githubusercontent.com/assets/10381896/26173876/6fbf3444-3b1b-11e7-9d47-67b2de4d8eac.png)
