### ISSUE TITLE
Enable clicking on calendar event to open managment modal

### ISSUE THREAD

**Issue by uladkasach** [personalcancertoolkit/openmrs-module-patientportaltoolkit#208]

**Comment by maurya** [comment]
This is not yet completed for Preventive Care

**Comment by uladkasach** [comment]
@maurya I've updated the title of this issue to reflect the scope that this issue was defined for, the original title was too broad since enabling modification of preventive care events is a whole separate task that was not yet specified to be completed.

Under this definition this issue is was completed for both preventive care and follow up care.
