### ISSUE TITLE
Update Ui to better icons and better look

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#230]

**Comment by maurya** [comment]
<img width="1521" alt="screen shot 2017-05-24 at 10 26 06 am" src="https://cloud.githubusercontent.com/assets/1560244/26408345/7f5d3e96-406b-11e7-8a64-f160c6f473fc.png">

**Comment by uladkasach** [comment]
Created minor design updates - created space between icons and text and changed cursor from default to pointer when hovering over header buttons. 

![image](https://cloud.githubusercontent.com/assets/10381896/26456294/a2af171e-413a-11e7-8439-b56e3677a57a.png)
