### ISSUE TITLE
Healthy Behavior Dashboard Layout -

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#242]
Image and general advise - incentive to enter data (could be text,images, badges - Can be general information about the average diet and exercise needed to be healthy) -> Form entry
small graph -> Bigger graphs and specialized data  
Friends -> Bigger data lists to friends

**Comment by uladkasach** [comment]
![image](https://cloud.githubusercontent.com/assets/10381896/26798336/096fbe42-49fe-11e7-98d7-0432ceaf54ea.png)

**Comment by uladkasach** [comment]
Progress has been made, presented at https://github.com/personalcancertoolkit/openmrs-module-healthybehaviors/issues/2
