### ISSUE TITLE
Increase diversity in HB images

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#250]
Should have good diversity for diet and physical exercise

**Comment by uladkasach** [comment]
Dr Haggstrom mentioned that current images are not bad: nutrition one is good, and exercise one is not bad as patients want to see themselves as healthy. 

Jennifer mentioned we may be able to find a more diverse image in yoga or tai chi. 

Prepare to do side by side testing.
