### ISSUE TITLE
Remove “Flex sigmoidoscopy” from follow up care events

### ISSUE THREAD

**Issue by uladkasach** [personalcancertoolkit/openmrs-module-patientportaltoolkit#269]
Per laylas email on July 17.

**Comment by jennifershivers** [comment]
We need to make sure that this change happens in both the dev and demo systems.

**Comment by uladkasach** [comment]
From the meeting on July 20, we discerned that in reality this means to remove Flex sigmoidoscopy. (We already have a distinct Colonoscopy event and Flex sigmoidoscopy is "no longer practiced")
