### ISSUE TITLE
Unable to find tables after successful installation of Patient Portal Toolkit

### ISSUE THREAD

**Issue by ajinkyagadewar** [personalcancertoolkit/openmrs-module-patientportaltoolkit#290]
ERROR - SqlExceptionHelper.logExceptions(146) |2017-10-10 09:51:30,843| Table 'mycare.patientportal_relation' doesn't exist

Also, no other tables related to patient portal exists in database.

What can be the issue?

**Comment by ajinkyagadewar** [comment]
ERROR - SqlExceptionHelper.logExceptions(146) |2017-10-10 14:56:48,133| Table 'mycare.patientportal_relation' doesn't exist

**Comment by uladkasach** [comment]
Could you outline your installation procedure?

Also, have you installed `openmrs-core` ?

**Comment by ajinkyagadewar** [comment]
Yes I have installed openmrs-core and all reference application modules.

**Comment by ajinkyagadewar** [comment]
bump

**Comment by maurya** [comment]
Hi @ajinkyagadewar, We are glad that you are interested. This is a reboot of an earlier project and is geared towards a specific use case. We are still developing this and is not yet ready for public consumption. There are some test databases we are using for development. We will make sure to include the installation steps once we make it a generic use case.

**Comment by ajinkyagadewar** [comment]
Thanks @maurya for the update.
