### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-patientportaltoolkit#307]
change permission granting box to say 
"medical profile"  

Add a bit more clarification on these choices.

**Comment by maurya** [comment]
<img width="1413" alt="screen shot 2018-02-01 at 12 25 46 pm" src="https://user-images.githubusercontent.com/1560244/35693074-13a539e0-074b-11e8-8a28-25a18d288e4b.png">

Updated in the localhost, will update the common server and close the ticket

**Comment by jennifershivers** [comment]
Ready after fixing the M in "My"

**Comment by maurya** [comment]
Impletemented
