### ISSUE TITLE
Admin Functionality - Categorize/create preventive care rules for different types of cancers

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#324]

**Comment by mipatil29** [comment]
![issue324](https://user-images.githubusercontent.com/34715305/46968739-0a2f5480-d082-11e8-9bfb-86701092ad8c.PNG)
![issue-324_edit](https://user-images.githubusercontent.com/34715305/46968740-0a2f5480-d082-11e8-99cf-39db83f1277d.PNG)
