### ISSUE TITLE
review links to determine if they are still active - colorectal 

### ISSUE THREAD

**Issue by jennifershivers** [personalcancertoolkit/openmrs-module-patientportaltoolkit#346]
Layla will do this.

**Comment by jennifershivers** [comment]
Layla sent the community link updates.  Maurya will update next.

**Comment by maurya** [comment]
Updated them https://github.com/personalcancertoolkit/openmrs-module-patientportaltoolkit/commit/86eb7a07fcf74935882f7d18ae2805562c3bb926
