### ISSUE TITLE
Create a request for sphere.regenstrief.org

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#395]
The production system should be hosted at sphere.regenstrief.org. Port 80 should redirect al paths to the same path on port 443 and this port should have a valid TLS certificate.

**Comment by maurya** [comment]
Sent request to CAITS waiting on it

**Comment by bmamlin** [comment]
They can discontinue pal.regenstrief.org

**Comment by maurya** [comment]
pal.regenstrief.org is discontinued, sphere.regenstrief.org is having issues, I've requested CAITS to investigate
