### ISSUE TITLE
Followup Care - Create a moniker ~ Auto FollowUp Care Event - and log them into the Event Table

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#445]

**Comment by bmamlin** [comment]
I believe the goal of this ticket was to log the generation of follow up appointments to the event log – i.e., whenever the system creates a follow up entry for a patient, an `auto_followup_care` event is added to the event log with details about the type of follow up and its date.

**Comment by bmamlin** [comment]
I agree. If events were getting stored to the database or were calculated once it might make sense, but If the follow up events are recalculated each time the calendar is viewed, then there isn't much point to logging these events. I'll go ahead and close this ticket.
