### ISSUE TITLE
Followup Care - Save the event when a patient edits the appointment with a new moniker - Patient Edited Event - Log them into the event table with previous data in the before JSON column

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#448]
When a user edits a followup appointment, generate a `edited_followup_appointment` event in the event log with data containing the previous & new values.

**Comment by PhilipAdeoye** [comment]
Logging a `EDITED_FOLLOWUP_APPOINTMENT` event with details similar to 

    {
      "patientId": "58",
      "procedure": "CEA Tests",
      "reminderId": "879",
      "newTargetDate": "05/16/2024",
      "oldTargetDate": "05/15/2024"
    }
