### ISSUE TITLE
MyCancerBuddy - Log -

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#450]
Any changes to Their name, description
Any interactions with other buddies,
Creating the profile button/process
Add Connection, Add request

**Comment by PhilipAdeoye** [comment]
- Creating the profile
-- clicked_MyCancerBuddiesRegister
- Changes to their name, description
-- clicked_MyCancerBuddies_ProfileCard_save
- Add Connection
-- clicked_MyCancerBuddies_addRelationshipButton
- Accepted Connection 
-- ACCEPTED_CONNECTION_REQUEST
