### ISSUE TITLE
Check Unload event and see if we can capture My Posts left event - https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#451]

**Comment by PhilipAdeoye** [comment]
The window beforeunload event fires when the page is about to be navigated away from. This is an opportunity to log the event . e.g

    jq(window).on('beforeunload', function() {
        logEvent('left_my_posts_event','');
        return true;
    });
