### ISSUE TITLE
Timeout should log us out and show a timeout error

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#467]
It would be nice to have a warning.

**Comment by PhilipAdeoye** [comment]
A possible approach for this one is to set a 30 minute timer that resets after every server interaction (page reload or ajax call).

If the timer gets to 25 minutes, it'll pop a modal that informs the user that their session will timeout in five minutes. This modal will also include a visible countdown timer.

The user will have the option to dismiss the modal or click a button that will refresh their session (and reset the timer)

If the user doesn't intervene and the timer times out, the modal will remain open and show a message that their session has timed out and they'll need to log in again
