### ISSUE TITLE
Hide Password field in the add patient form -  generate a random password - if possible trigger the forgot password and send an email

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#470]
Make sure to send the username and password email i.e

Hello user,

Your password has been changed based on your request. Your new credentials are:

username: {username}
password: {password}

**Comment by bmamlin** [comment]
Hiding the password field and loading it with a random value could be done like this:

```html
<input id="password" type="hidden" />
<script>
document.getElementById("password").value = crypto.randomUUID()
</script>
```

(`crypto.randomUUID()` is supported in [most browsers](https://caniuse.com/mdn-api_crypto_randomuuid) and only needs to work on browsers used by the research team who are creating patient accounts)
