### ISSUE TITLE
Change in Cancer Stage not recording properly

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#474]
Was able to recreate in a newly created account

**Comment by maurya** [comment]
This happens when all information in the form is not filled properly

**Comment by maurya** [comment]
PCP details should be not required and the form should submit without failing due to that

**Comment by PhilipAdeoye** [comment]
As of May 10 2023, the PCP details are not required, the form submits without failing, and the change in cancer stage appears to be working correctly
