### ISSUE TITLE
Symptom management navigation is broken

### ISSUE THREAD

**Issue by bmamlin** [personalcancertoolkit/openmrs-module-patientportaltoolkit#480]
Symptom management removes symptoms still appearing in next symptom list.

The "previous" and "next" buttons appear and disappear unexpectedly when moving through symptoms.

Code for this is [here](https://github.com/personalcancertoolkit/symptom-management/blob/master/public/index.php#L229-L367).

**Comment by bmamlin** [comment]
@maurya have you had any luck troubleshooting this? I've tried to walk through the logic and I'm starting to get my head around parts of it, but I haven't yet found a solution for it.

**Comment by maurya** [comment]
After discussion with @bmamlin - it was identified that the code uses SQL to generate the list of symptoms for symptom reporting but did not check if this list was from an updated cancer specific list. We implemented a fix where the SQL checks if the symptom is present in the colorectal cancer list in `cancer_symptoms` table.

Fix implemented here - https://github.com/personalcancertoolkit/symptom-management/commit/8b2cee64518c0c422eef0ca91e2d2c66e72355ba
