### ISSUE TITLE
Change password check what requirements and put them in the interface

### ISSUE THREAD

**Issue by bmamlin** [personalcancertoolkit/openmrs-module-patientportaltoolkit#482]

**Comment by maurya** [comment]
Non correct password submission shouldn't submit

**Comment by bmamlin** [comment]
1. Change password page shows password requirements
2. Form cannot be submitted if requirements are not met
3. If the password is not changed after submission, the page should show an error (instead of looking like the change succeeded)
4. Ideally, the current password should be required before the new password & confirmation
