### ISSUE TITLE
Change the text of reset password - To make sure if there is no link, what to do

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#483]

**Comment by maurya** [comment]
Hello sample6 kummamuru,

We have received a password change request for your SPHERE personal cancer toolkit account.

If this was you, please click on this LINK to change your password -https://sphere.regenstrief.org/openmrs/ws/patientportaltoolkit/confirmForgotPasswordEmail/ef962ab4-9fff-488d-83da-bc3f0d54f9fe/sample6@kummamuru.com

 If you did not request a password change request, do not click on the link above. Please notify the study team at [sphere@iupui.edu](mailto:sphere@iupui.edu).

**Comment by bmamlin** [comment]
Proposal:
```
Hello sample6 kummamuru,

We have received a password change request for your SPHERE personal 
cancer toolkit account.

If this was you, please click on this LINK to change your password:

https://sphere.regenstrief.org/openmrs/ws/patientportaltoolkit/confirmForgotPasswordEmail/ef962ab4-9fff-488d-83da-bc3f0d54f9fe/sample6@kummamuru.com

(If the link on the line above is not clickable, you can copy it into your browser)

 If you did not request a password change request, do not click on the link 
above. Please notify the study team at [sphere@iupui.edu](mailto:sphere@iupui.edu).
```

**Comment by maurya** [comment]
done
