### ISSUE TITLE
Date box should not be in fixed position should move when scrolling

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#496]

**Comment by maurya** [comment]
Made sure the date picker disappears if scrolling

**Comment by bmamlin** [comment]
@maurya, it looks like there's a _place()_ method on Bootstrap's datepicker that might help ([reference](https://stackoverflow.com/questions/20488734/bootstrap-datepicker-does-not-scroll-when-scrolling-the-modal))
