### ISSUE TITLE
Ensure prod and test environments are running omod compiled from tagged version of repository.

### ISSUE THREAD

**Issue by bmamlin** [personalcancertoolkit/openmrs-module-patientportaltoolkit#504]
We need to make sure prod (and test) environments are running a copy of the omod built from a tagged version of the repository.

**Comment by maurya** [comment]
Created tag -  1.1 https://github.com/personalcancertoolkit/openmrs-module-patientportaltoolkit/tree/1.1/ and installed the omod in both production and personalcancertoolkit.org
