### ISSUE TITLE
Preventive Care - If a recommended date is modified to a different date - the next appointment should adjust based on the interval

### ISSUE THREAD

**Issue by bmamlin** [personalcancertoolkit/openmrs-module-patientportaltoolkit#514]
After some discussion with David, we decided to use this logic:

Look in the database for the most recent date for the preventative care item of concern up to one year from today's date. If found, use the date of that item as the anchor date; otherwise, use the join date as the anchor date. Then calculate intervals using this anchor date.

**Comment by PhilipAdeoye** [comment]
For each procedure (preventative care item), 

- look twelve months into the future starting tomorrow and search the database for any PreventativeCareEvents that haven't been completed yet (status = 0) . Pick the one that's farthest out
- look into the past (including today) and search the database for any completed (status = 1) PreventativeCareEvents. Pick the most recent one.

If a future event exists, use its target date as the anchor date. If a future one doesn't exist, pick the completed one in the past, and use its completed date as the anchor date. If neither exist, use the patient's join date as the anchor date.

To prevent duplicates, when generating the hypothetical recommended dates, check each recommended date against the PreventativeCareEvents in the database (for the same procedure). If the event is completed, check the recommended date against the event's completed date, but if it is in the future, check the recommended date against the event's target date.
