### ISSUE TITLE
Caregiver seeing their own symptom management data instead of the patient's data

### ISSUE THREAD

**Issue by PhilipAdeoye** [personalcancertoolkit/openmrs-module-patientportaltoolkit#534]
With a caregiver account (non-patient & non-admin) created when a patient adds a brother/sister/caregiver as a connection, when viewing a patient's record, the general history, treatments, communities, etc show the patient's records. Except the symptom management. Symptom management shows the caregiver's own symptoms

**Comment by bmamlin** [comment]
When Caregiver views symptom management screen, they now see symptom data for the patient (not themselves).
