### ISSUE TITLE
Send reminders of upcoming surveillance tests

### ISSUE THREAD

**Issue by bmamlin** [personalcancertoolkit/openmrs-module-patientportaltoolkit#535]
Since upcoming surveillance tests are computed "on the fly" (i.e., when the future surveillance tests are being viewed), we cannot simply query the database for upcoming tests; rather, we will need to run through all active patients (e.g., daily), compute their upcoming surveillance tests, and then send a notification if there are imminent tests.

> Greeting from the SPHERE program. Based on available information, it looks like
> you have an upcoming appointment. Note this is not linked to your medical record,
> so please verify with your provider(s). You can view your upcoming tests in SPHERE 
> by click on <this link>

We would want to persist something (e.g., when notification is sent) to prevent re-sending the notification.

* When would a notification be sent?
  * One month beforehand
  * One week beforehand
  * Two weeks after
* What would the content of the notification be?
  * Make aware of recommendation of upcoming test
  * Remind them to mark a recent (previous) test as completed
  * Include disclaimer that SPHERE is not linked to medical record
  * Include brief instructions on how to navigate – e.g., "After logging in, click on 'My Medical Profile' at the top and then select the 'Follow up Care' tab to see your recent and upcoming appointments."
* Add event log entries when notifications are sent
  * surveillance_reminder_1m
  * surveillance_reminder_1w
  * surveillance_reminder_follow_up
* Extra credit: see if we could support a link directly to "Follow up Care" tab of medication profile

**Comment by PhilipAdeoye** [comment]
Hello Michael, 

You may be due for a recommended follow-up appointment with your doctor in a week to a month. 

Or, you may have visited your doctor recently for a recommended follow-up appointment. 

Please know that we don’t have access to your medical records, so we don’t know specific details. 

Log in to the SPHERE website (sphere.regenstrief.org) and check your Messages for more information about these appointments. 

Thank you,
The SPHERE Team
