### ISSUE TITLE
Allow users to login using email address

### ISSUE THREAD

**Issue by bmamlin** [personalcancertoolkit/openmrs-module-patientportaltoolkit#551]
In the [CustomLoginPageController](https://github.com/personalcancertoolkit/openmrs-module-patientportaltoolkit/blob/9bfde53b4eaf756823805806774690c0d93ee26c/omod/src/main/java/org/openmrs/module/patientportaltoolkit/page/controller/CustomLoginPageController.java#L86), before authenticating, we could check if the username contains an at sign (@) and, if so, search (case-insensitively) for a matching email address and, if found, substitute the associated username before authenticating.

**Comment by PhilipAdeoye** [comment]
When validating the login, we attempt to login using the username and password. If it fails, assume the username is an email address and try to find a person with that email. If a person is found with that email, get the username for that person and use it to log them in

**Comment by bmamlin** [comment]
> When validating the login, we attempt to login using the username and password. If it fails, assume the username is an email address and try to find a person with that email. If a person is found with that email, get the username for that person and use it to log them in

Why try to log in with an email address? Usernames should never contain an at-sign and emails will always contain an at-sign, so `username.contains("@")` should reliably distinguish between email and non-email entries.

Wouldn't something like this work just before authentication?
```java
if (username.contains("@")) {
  // returns original string if no user is found with given email address
  username = userWithEmailAddress(username);
}
```

**Comment by PhilipAdeoye** [comment]
Yeah, I thought about that, and it's clever and simple, but I wanted a more general solution
